dist: trusty
sudo: false
language: ruby
rvm:
  - 2.3.3
services:
  - postgresql
addons:
  postgresql: 9.6
before_script:
  - psql -c 'CREATE DATABASE db_schema_test;' -U postgres
  - psql -c 'CREATE DATABASE db_schema_test2;' -U postgres
